In [1]:
import pandas as pd
import tensorflow as tf
import numpy as np

dataframe = pd.read_csv("C:\\Users\\ibels\\Iris\\Data\\iris_train_features.csv", header=None)
dataset = dataframe.values
X = dataset[:,0:4].astype(float)


import pandas as pd
dataframe = pd.read_csv("C:\\Users\\ibels\\Iris\\Data\\iris_train_label.csv", header=None)
dataset = dataframe.values
Y = dataset[:,0:3].astype(int)





input_layer = 1
#hidden_layer1 = 1
#hidden_layer2 =4 
output_layer =3




model = tf.keras.Sequential();
model.add(tf.keras.layers.Dense(input_layer,input_shape=(4,),activation=tf.nn.relu,name='Input_Layer',kernel_regularizer='l1'))
model.add(tf.keras.layers.Dense(output_layer,activation='softmax',name='Output_layer',kernel_regularizer='l1'))

model.summary()



model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])


writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())
writer.close()

#xx = X[1,].reshape(1,4)
#yy = Y[1,].reshape(1,3)


model.fit(X,Y,epochs=10000,batch_size=105)


model.get_weights()


ModuleNotFoundError: No module named 'pandas'

In [10]:
W=model.get_weights()
w1=tf.constant(W[0])
b1=tf.constant(W[1])
w2=tf.constant(W[2])
b2=tf.constant(W[3])

x=tf.placeholder(tf.float32)

h=tf.maximum(0.0,tf.add(tf.matmul(x,w1),b1))
out=tf.nn.softmax(tf.add(tf.matmul(h,w2),b2))

error=[]
with tf.Session() as sess:
    for i in range(105):
        values={
            x:X[i,].reshape(1,4),
            }
        print(sess.run(out,feed_dict=values), Y[i,])
        #mismatch=np.abs(np.argmax(sess.run(out,feed_dict=values))- np.argmax(Y[i,]))
        #if mismatch != 0 :
         #   print(sess.run(out,feed_dict=values),Y[i,])


[[2.1069094e-14 8.5354159e-03 9.9146456e-01]] [0 0 1]
[[9.8373067e-01 1.6267525e-02 1.7737522e-06]] [1 0 0]
[[1.4579907e-14 7.6184552e-03 9.9238151e-01]] [0 0 1]
[[0.00741306 0.9864231  0.0061639 ]] [0 1 0]
[[8.7813497e-01 1.2183037e-01 3.4608092e-05]] [1 0 0]
[[6.7438354e-04 9.8132575e-01 1.7999789e-02]] [0 1 0]
[[9.6450096e-01 3.5493538e-02 5.5476989e-06]] [1 0 0]
[[3.8943558e-13 2.0926984e-02 9.7907305e-01]] [0 0 1]
[[1.7429344e-04 9.6740627e-01 3.2419465e-02]] [0 1 0]
[[5.5247528e-04 9.7980165e-01 1.9645866e-02]] [0 1 0]
[[0.15175644 0.84697413 0.00126945]] [0 1 0]
[[9.6719956e-01 3.2795478e-02 4.9405344e-06]] [1 0 0]
[[0.0270882  0.9695572  0.00335461]] [0 1 0]
[[1.4579907e-14 7.6184552e-03 9.9238151e-01]] [0 0 1]
[[9.8373067e-01 1.6267525e-02 1.7737522e-06]] [1 0 0]
[[2.6268872e-05 9.2838442e-01 7.1589366e-02]] [0 1 0]
[[9.8373067e-01 1.6267525e-02 1.7737522e-06]] [1 0 0]
[[0.03100936 0.96585166 0.00313906]] [0 1 0]
[[2.6140110e-15 4.4780993e-03 9.9552190e-01]] [0 0 1]
[[5.319224